# Generated by Django 5.2.4 on 2025-07-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='num_votes',
        ),
        migrations.AddField(
            model_name='movie',
            name='isAdult',
            field=models.BooleanField(null=True),
        ),
    ]
