# Generated by Django 5.2.4 on 2025-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_num_votes_movie_isadult'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='titleType',
            field=models.CharField(default='movie', max_length=255),
        ),
    ]
