# Generated by Django 5.2.4 on 2025-08-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBoot', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'user'), ('model', 'model')], default='user', max_length=5),
        ),
    ]
